version: '3'

services:
  db-tarefa:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: tarefa
      POSTGRES_DB: tarefa
    ports:
      - 5432:5432
    restart: always
    networks:
      - tarefa
  minio-tarefa:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server /data
    ports:
      - 9000:9000
    networks:
      - tarefa

networks:
  tarefa:
    driver: bridge