server:
  port: 8081

spring:
  application:
    name: documentoservice
  servlet:
    multipart.max-file-size: 50MB
    multipart.max-request-size: 50MB
application:
  minio:
    url: http://localhost:9000
    accessKey: minio
    secretKey: minio123
    bucketName: documentos
