spring:
  application:
    name: tarefaservice

  datasource:
    url: jdbc:postgresql://localhost/tarefa?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: tarefa
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate-ddl: true
    show-sql: true

  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    drop-first: false

logging:
  level:
    liquibase: INFO
    ROOT: INFO
    com.jeanpandolfi.tarefaservice: DEBUG

application:
  feign:
    documento: http://localhost:8081

  elasticsearch:
    url: localhost:9200
